"""Add back_populates

Revision ID: fa99be28e7a2
Revises: f18a4ec6e42e
Create Date: 2025-04-18 15:07:50.950592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa99be28e7a2'
down_revision: Union[str, None] = 'f18a4ec6e42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
